name: meloplay
description: Meloplay is a local music player app that plays music from your device built with Flutter.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.1+1

environment:
    sdk: '>=3.0.6 <4.0.0'

dependencies:
    bloc: ^8.1.2 # state management
    flutter:
        sdk: flutter # flutter sdk
    flutter_bloc: ^8.1.3 # state management
    flutter_staggered_animations: ^1.1.1 # animation
    get_it: ^7.6.7 # dependency injection
    hive: ^2.2.3 # local database
    hive_flutter: ^1.1.0 # local database
    just_audio: ^0.9.36 # audio player
    just_audio_background: ^0.0.1-beta.11 # audio player background
    on_audio_query: ^2.9.0 # get songs from device
    package_info_plus: 4.2.0 # get app info
    permission_handler: ^11.2.0 # get permission
    rxdart: ^0.27.7 # stream
    share_plus: ^7.2.2 # share song
    url_launcher: ^6.2.4 # open url
    dio: ^4.0.0
    json_annotation: ^4.8.1
    json_serializable: ^6.1.5
    build_runner: ^2.4.9

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.1 # linter
    flutter_launcher_icons: ^0.13.1 # app icon generator

flutter:
    uses-material-design: true
    assets:
        - assets/icon/

flutter_launcher_icons:
    image_path: 'assets/icon/icon.png'
    android: true
    ios: true
# dart pub get
# dart run flutter_launcher_icons
